---
dist: xenial
language: python
python: "2.7"

sudo: true

services:
  - docker

env:
  - awx_version: 9.1.0
  - awx_version: 9.0.1
  - awx_version: 9.0.0

install:
  - pip install ansible docker-compose
  - pip list
  - which ansible-playbook
  - ls -a
  - ansible -m debug -a var=ansible_python_interpreter localhost
  - ansible-playbook install_awx.yml -e awx_version=$awx_version

script:
  - true
