---
dist: xenial
language: python
python: "3.6"

sudo: true

services:
  - docker

env:
  - awx_version: 9.1.0
  - awx_version: 9.0.1
  - awx_version: 9.0.0

install:
  - pip install ansible docker-compose
  - which ansible-playbook
  - /home/travis/virtualenv/python3.6.7/bin/ansible-playbook install_awx.yml -e awx_version=$awx_version

script:
  - true
