---
dist: xenial

sudo: true

services:
  - docker

env:
  - awx_version: 9.1.0
  - awx_version: 9.0.1
  - awx_version: 9.0.0

install:
  - sudo apt -y update
  - sudo apt -y install python python-pip
  - sudo pip install ansible docker-compose ansible-tower-cli
  - sudo pip list
  - which ansible-playbook
  - ls -a
  - ansible -m debug -a var=ansible_python_interpreter localhost
  - ansible-playbook install_awx.yml -e awx_version=$awx_version
  - sleep 150
  - ansible-playbook configure_awx.yml
  - sudo docker exec -it awx_task ls /var/lib/awx/projects/
  - sudo docker exec -it awx_task cat /tmp/tmp_tree

script:
  - true
