---
dist: xenial

sudo: true

services:
  - docker

env:
  - awx_version: 9.1.0
  - awx_version: 9.0.1
  - awx_version: 9.0.0
  - awx_version: 8.0.0
  - awx_version: 7.0.0
  - awx_version: 6.1.0
  - awx_version: 6.0.0
  - awx_version: 5.0.0

install:
  - sudo apt -y update
  - sudo apt -y install python python-pip
  - sudo pip install ansible docker-compose ansible-tower-cli
  - sudo pip list
  - which ansible-playbook
  - ls -a
  - ansible -m debug -a var=ansible_python_interpreter localhost
  - ansible-playbook install_awx.yml -e awx_version=$awx_version
  - sudo docker exec -it awx_task yum -y install tree
  - sleep 250
  - sudo docker exec -it awx_task sed -i 's/when:\ roles_enabled/#when: roles_enabled/g' /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/playbooks/project_update.yml
  - ansible-playbook configure_awx.yml


script:
  - sleep 60
  - sudo docker exec -it awx_task tree /var/lib/awx/projects/
  - sudo docker exec -it awx_task tree /var/lib/awx/projects/ | grep -q 'geerlingguy.java' || (echo "Role has not been downloaded" && false)
  - sudo docker exec -it awx_task cat /tmp/tree
  - sudo docker exec -it awx_task cat /tmp/tree | grep -q 'geerlingguy.java' || (echo "Role is not present in execution folder" && false)
