- hosts: localhost
  vars:
    awx_organizations:
      - name: "Test"
    awx_projects:
      - name: "Command Center"
        organization: "Exploit"
        scm_type: "git"
        scm_url: "https://github.com/Nani-o/awx-test"
        scm_clean: True
        scm_update_on_launch: True
    awx_inventories:
      - name: "Test"
        organization: "Test"
    awx_host: "http://127.0.0.1"
    awx_username: "admin"
    awx_password: "password"
  tasks:
    - name: Create organizations
      tower_organization:
        name: "Test"
        state: present
        tower_host: "{{ awx_host }}"
        tower_password: "{{ awx_password }}"
        tower_username: "{{ awx_username }}"
        tower_verify_ssl: False

    - name: Create projects
      tower_project:
        name: "Test"
        organization: "Test"
        scm_type: "git"
        scm_url: "https://github.com/Nani-o/awx-test"
        scm_clean: True
        scm_update_on_launch: True
        state: present
        tower_host: "{{ awx_host }}"
        tower_password: "{{ awx_password }}"
        tower_username: "{{ awx_username }}"
        tower_verify_ssl: False
      register: result

    - name: Wait for the project to be status=successful
      uri:
        url: "{{ awx_host }}/api/v2/projects/{{ result.id }}/"
        method: GET
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        validate_certs: false
        force_basic_auth: true
        return_content: true
      register: result
      until: result.json.summary_fields.last_update is defined and result.json.summary_fields.last_update.status == "successful"
      retries: 60
      delay: 1

    - name: Create inventories
      tower_inventory:
        name: "Test"
        organization: "Test"
        tower_host: "{{ awx_host }}"
        tower_password: "{{ awx_password }}"
        tower_username: "{{ awx_username }}"
        tower_verify_ssl: False

    - name: Create job template
      tower_job_template:
        name: "Test"
        job_type: "run"
        inventory: "Test"
        project: "Test"
        playbook: "plays/test.yml"
        state: "present"
        tower_host: "{{ awx_host }}"
        tower_password: "{{ awx_password }}"
        tower_username: "{{ awx_username }}"
        tower_verify_ssl: False

    - name: Run job
      tower_job_launch:
        job_template: "Test"
        tower_host: "{{ awx_host }}"
        tower_password: "{{ awx_password }}"
        tower_username: "{{ awx_username }}"
        tower_verify_ssl: False
      register: job
...
