---
- hosts: localhost
  become: True
  tasks:
    - name: "Clone repository"
      git:
        clone: True
        dest: "/root/awx"
        repo: "https://github.com/ansible/awx"
        version: "devel"
        update: False
        force: True

    - name: "Run awx install playbook"
      command: "/home/travis/virtualenv/python3.6.7/bin/ansible-playbook -i inventory install.yml -e dockerhub_version={{ awx_version }}"
      args:
        chdir: "/root/awx/installer"
...
