---
- hosts: localhost
  become: True
  tasks:
    - name: "Clone repository"
      git:
        clone: True
        dest: "/root/awx"
        repo: "https://github.com/ansible/awx"
        version: "devel"
        update: False
        force: True

    - name: "Run awx install playbook"
      command: "ansible-playbook -i inventory install.yml -e dockerhub_version={{ awx_version }} -e custom_venv_dir=/home/travis/virtualenv"
      args:
        chdir: "/root/awx/installer"
...
